global:
route:
  receiver: 'alertmanager-bot'
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

# Estudar comportamentos quando cria-se rotas específicas.
# routes:
# - receiver: AlertaDataBase
#   match:
#     team: mongodb

# - receiver: AlertaWebApi
#   match:
#     team: webapi

receivers:
- name: 'alertmanager-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'