global:

route:
  receiver: 'alertmanager webhook'

  routes:
  # group_by: ['alertname']
  # group_wait:      15s
  # group_interval:  15s
  # repeat_interval: 1m
  - receiver: 'alertmanager-notifier-webhook'

receivers:
- name: 'alertmanager-notifier-webhook'
  webhook_configs:
  - url: http://alertmanager-notifier:8899/alert

- name: 'alertmanager webhook'
  webhook_configs:
  - url: http://alertmanager-notifier:8899/alert
