global:

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

  routes:
  - receiver: 'alertmanager-webapi'
    match:
      team: webapi

receivers:
- name: 'alertmanager-webapi'
  webhook_configs:
  - url: http://alertmanager-notifier:8899/alert

- name: 'default'
  webhook_configs:
  - url: http://alertmanager-notifier:8899/alert



# global:

# route:
#   group_by: ['alertname']
#   group_wait:      15s
#   group_interval:  15s
#   repeat_interval: 1m
#   receiver: 'alertmanager webhook'

#   routes:
#   - receiver: 'alertmanager-notifier-webhook'

# receivers:
# - name: 'alertmanager-notifier-webhook'
#   webhook_configs:
#   - url: http://alertmanager-notifier:8899/alert

# - name: 'alertmanager webhook'
#   webhook_configs:
#   - url: http://alertmanager-notifier:8899/alert

